#!/bin/sh
DOTFILES="$HOME/.files/dotfiles"
for file in $(find $DOTFILES -name '.*' -maxdepth 1)
do
    f=$(basename $file)
    if [[ $f == ".DS_Store" ]]; then
        continue
    fi
    echo "Creating symlink to $f in $HOME."
    ln -sf "$DOTFILES/$f" "$HOME"
done
