#!/bin/sh
DOTFILES="$HOME/.files/dotfiles/"
for file in $(find $DOTFILES -name '.*')
do
    file=$(basename $file)
    echo "Creating symlink to $file in $HOME."
    ln -sf "$DOTFILES/$file" "$HOME/$file"
done
